### ISSUE TITLE
Readme clarification: Endpoint callbacks are required to be in server.js

### ISSUE THREAD

**Issue by brettinternet** [DevMountain/node-assessment-retired#5]
While the current `readme.md` does suggest the endpoints should be declared in `server.js`, it doesn't clarify the distinction that the callback functions with `res`/`response` are expected to be in `server.js`.

Suggested clarification:

> ** Note: You should invoke these methods (from users.js) in your userCtrl.js, however your endpoint callbacks with req and response should be written in your server.js.

I'm not sure the way I've phrase it above sounds quite right. But we need to clarify that our endpoint callbacks `function(req, res)` must be in the `server.js` and not reference a function in `userCtrl.js` for the tests to pass.

**Comment by asBrettisay** [comment]
I tried to address this with [1fac910](https://github.com/DevMountain/node-assessment/commit/1fac9102b28cd647f1745187322fc53d72fdd02d)
